AWSTemplateFormatVersion: '2010-09-09'

Description: Create a VPC for CloudFormation practice

Resources:

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.50.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

      Tags:
        - Key: Name
          Value: My-Practice-VPC

Outputs:

  VPCId:
    Description: VPC ID
    Value: !Ref MyVPC

  VPCCIDR:
    Description: VPC CIDR Block
    Value: 10.50.0.0/16
